version: '2'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: tecken-loadtest:latest
    env_file:
      - my.env
    volumes:
      - $PWD:/app
    command: /bin/bash
